import { AlertTriangle, MessageCircle, Clock } from 'lucide-react';
import { Badge } from './ui/Badge';

export function LowStockBanner({ products }) {
  // Logic remains untouched as per your request
  const lowStockProducts = products.filter(p => p.stock <= p.minStock);

  // Expiry Alerts Logic
  const today = new Date();
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(today.getDate() + 30);

  const expiringSoon = products.filter(p => {
    if (!p.expiryDate) return false;
    const expDate = new Date(p.expiryDate);
    return expDate <= thirtyDaysFromNow && expDate >= today;
  });

  const expired = products.filter(p => {
    if (!p.expiryDate) return false;
    return new Date(p.expiryDate) < today;
  });

  // Combined check for visibility
  if (lowStockProducts.length === 0 && expiringSoon.length === 0 && expired.length === 0) return null;

  const outOfStock = lowStockProducts.filter(p => p.stock === 0);
  const lowStock = lowStockProducts.filter(p => p.stock > 0);

  const handleBulkAlert = () => {
    const phone = import.meta.env.VITE_WHATSAPP_NUMBER || "";
    let message = `*NexusOS Inventory Intelligence*\n\n`;
    
    if(expired.length > 0) {
      message += `⚠️ *EXPIRED ITEMS*\n`;
      expired.forEach(p => message += `• ${p.name} (Expired)\n`);
    }
    
    message += `\n🔴 *OUT OF STOCK*\n`;
    outOfStock.forEach(p => message += `• ${p.name}\n`);
    
    message += `\n🟠 *LOW STOCK WARNING*\n`;
    lowStock.forEach(p => message += `• ${p.name}: ${p.stock} left\n`);
    
    message += `\n*Action Required:* Restock and verify inventory immediately.\n\n_Generated by NexusOS ERP_`;
    const url = `https://wa.me/${phone.replace("+", "")}?text=${encodeURIComponent(message)}`;
    window.open(url, "_blank");
  };

  return (
    <div className="bg-white border border-slate-100 rounded-[2rem] p-4 flex flex-col lg:flex-row items-center justify-between gap-6 shadow-xl shadow-slate-200/40 mb-8 animate-in slide-in-from-top-6 duration-700 ease-out shrink-0">
      <div className="flex flex-col md:flex-row items-center gap-5 w-full">
        {/* Authoritative Badge Section */}
        <div className="flex items-center gap-3 px-4 py-2 bg-slate-900 text-white rounded-2xl shadow-lg shadow-slate-200 shrink-0 transform transition-transform duration-500 hover:scale-105">
          <AlertTriangle className="w-4 h-4 text-amber-400 animate-pulse" />
          <div className="flex flex-col">
            <span className="text-[10px] font-black uppercase tracking-[0.2em] leading-none">Intelligence</span>
            <span className="text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1">System Alerts</span>
          </div>
        </div>

        {/* Scrollable Badge Container */}
        <div className="flex flex-wrap items-center gap-2 overflow-x-auto scrollbar-hide py-1 max-w-4xl">
          {expired.map(p => (
            <Badge key={p._id} variant="danger" className="animate-pulse flex items-center gap-1.5 border-rose-200">
              <Clock className="w-3 h-3" />
              <span className="text-[9px] font-black uppercase">Expired: {p.name}</span>
            </Badge>
          ))}
          
          {outOfStock.map(p => (
            <Badge key={p._id} variant="danger" className="flex items-center gap-1.5 border-rose-100 bg-rose-50/50">
              <div className="w-1.5 h-1.5 bg-rose-500 rounded-full animate-ping" />
              <span className="text-[9px] font-black uppercase">Out: {p.name}</span>
            </Badge>
          ))}
          
          {expiringSoon.map(p => (
            <Badge key={p._id} variant="warning" className="flex items-center gap-1.5 border-amber-100">
              <span className="text-[9px] font-black uppercase">Expiring: {p.name}</span>
            </Badge>
          ))}
          
          {lowStock.map(p => (
            <Badge key={p._id} variant="warning" className="flex items-center gap-1.5 border-amber-100 opacity-90">
              <span className="text-[9px] font-black uppercase">Low: {p.name} ({p.stock})</span>
            </Badge>
          ))}
        </div>
      </div>

      {/* WhatsApp Button - Pro Styling */}
      <button
        onClick={handleBulkAlert}
        className="group flex items-center gap-3 px-6 py-3 bg-slate-900 text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] hover:bg-blue-600 transition-all duration-500 shadow-xl shadow-slate-200 active:scale-95 whitespace-nowrap"
      >
        <MessageCircle className="w-4 h-4 group-hover:rotate-12 transition-transform" />
        WhatsApp Admin
      </button>
    </div>
  );
}